name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: abystoma/external-workflow@355aebbea9f862df562f95426a2c1128d7bfbb7f
      - name: Greetings
        run: echo "$(<greeting.txt)"
